# ---------- Build stage ----------
FROM eclipse-temurin:17-jdk-jammy AS build
WORKDIR /app

# Copy everything (pom.xml, src, mvnw, .mvn)
COPY . .

# Build Spring Boot jar
RUN ./mvnw clean package -DskipTests


# ---------- Runtime stage ----------
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app

# Copy ONLY the jar from build stage
COPY --from=build /app/target/*jar app.jar

EXPOSE 8000

ENTRYPOINT ["java","-jar","app.jar"]
